version: 2
updates:
  # Temporarily disable all updates during workflow reset
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 0  # DISABLED for reset
    labels:
      - "dependencies"
      - "npm"
    
  # Temporarily disable all updates during workflow reset
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 0  # DISABLED for reset
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore non-critical dependencies
      - dependency-name: "pytest*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pandas"
        update-types: ["version-update:semver-minor"]
      
  # Temporarily disable all updates during workflow reset
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 0  # DISABLED for reset
    labels:
      - "dependencies"
      - "docker"
      
  # Temporarily disable all updates during workflow reset
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 0  # DISABLED for reset
    labels:
      - "dependencies"
      - "github-actions"