version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "next"
        versions: ["<14"]  # ignore ancient bumps
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "monthly" }
