title = "Hardened gitleaks config (v8) - ZERO TOLERANCE"

[allowlist]
description = "Allowed, non-sensitive patterns & paths only"
paths = [
  '''^docs/examples/''',
  '''\.env\.example$'''
]
regexes = [
  # Explicit placeholders only (safe to allow)
  '''YOUR_SUPABASE_(ANON|SERVICE)_KEY''',
  '''YOUR_MAPBOX_TOKEN''',
  '''YOUR_GITHUB_PAT''',
  '''\*\*\*REDACTED[_A-Z]*\*\*\*''',
  '''YOUR_[A-Z_]+_KEY''',
  '''placeholder[_-]key''',
  '''REDACTED'''
]

[[rules]]
id = "supabase-service-role"
description = "Supabase service role key"
regex = '''eyJ[a-zA-Z0-9_\-]{10,}\.[a-zA-Z0-9_\-]{10,}\.[a-zA-Z0-9_\-]{10,}'''
tags = ["supabase","key","jwt"]
[rules.allowlist]
regexes = ['''YOUR_SUPABASE_SERVICE_KEY''', '''\*\*\*REDACTED[_A-Z]*\*\*\*''', '''REDACTED''']

[[rules]]
id = "supabase-access-token" 
description = "Supabase access token"
regex = '''sbp_[A-Za-z0-9]{40,}'''
tags = ["supabase","token"]
[rules.allowlist]
regexes = ['''YOUR_SUPABASE_ACCESS_TOKEN''', '''\*\*\*REDACTED[_A-Z]*\*\*\*''', '''REDACTED''']

[[rules]]
id = "mapbox-token"
description = "Mapbox public/private token"
regex = '''(pk|sk)\.[A-Za-z0-9]{40,}'''
tags = ["mapbox","token"]
[rules.allowlist]
regexes = ['''YOUR_MAPBOX_TOKEN''', '''\*\*\*REDACTED[_A-Z]*\*\*\*''', '''REDACTED''']

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[A-Za-z0-9]{36}'''
tags = ["github","token"]
[rules.allowlist]
regexes = ['''YOUR_GITHUB_PAT''', '''\*\*\*REDACTED[_A-Z]*\*\*\*''', '''REDACTED''']

[[rules]]
id = "generic-bearer"
description = "Generic Bearer token"
regex = '''(?i)bearer\s+[A-Za-z0-9\-\._~\+\/]+=*'''
tags = ["bearer","generic"]
[rules.allowlist]
regexes = ['''\*\*\*REDACTED[_A-Z]*\*\*\*''', '''YOUR_BEARER_TOKEN''', '''REDACTED''']