# .polaris.yaml - Polaris configuration for AI-AAS Hardened Lakehouse
# Documentation: https://polaris.docs.fairwinds.com/customization/configuration/

# Global settings
displayName: "AI-AAS Hardened Lakehouse Security Audit"
resources:
  include:
    - "*.yaml"
    - "*.yml"

# Check configuration
checks:
  # Security
  runAsNonRoot: warning
  runAsUser: warning
  readOnlyRootFilesystem: warning
  allowPrivilegeEscalation: warning
  runAsRootAllowed: danger
  insecureCapabilities: danger
  dangerousCapabilities: danger
  
  # Resources
  cpuRequestsMissing: warning
  memoryRequestsMissing: warning
  cpuLimitsMissing: warning
  memoryLimitsMissing: warning
  
  # Networking
  hostNetworkSet: danger
  hostPIDSet: danger
  hostIPCSet: danger
  
  # Images
  tagNotSpecified: warning
  pullPolicyNotAlways: ignore  # Allow latest for development
  
  # Probes
  readinessProbeMissing: warning
  livenessProbeMissing: warning

# Exemptions (platform-specific)
exemptions:
  - namespace: aaas
    controllerNames:
      - trino
    rules:
      - readOnlyRootFilesystem  # Trino needs write access for temp files

# Mutation settings (for auto-fix)
mutations:
  - pullPolicyNotAlways
  - tagNotSpecified

# Output settings
disallowExemptions: false
disallowConfigExemptions: false