packages:
  - "apps/*"
  - "services/*" 
  - "packages/*"
  - "infra/*"
  - "infra/mcp-servers/*"
  - "components/*"
  - "db"
  - "dq"
  - "supabase"
  - "docs-site"
  - "platform/*"
  - "observability/*"
