apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8scontainerprobes
spec:
  crd:
    spec:
      names:
        kind: K8sContainerProbes
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8scontainerprobes
        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          not c.livenessProbe
          msg := sprintf("container %v missing livenessProbe", [c.name])
        }
        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          not c.readinessProbe
          msg := sprintf("container %v missing readinessProbe", [c.name])
        }