name: build-dbt-runner
on:
  push:
    branches: [ "main" ]
    paths:
      - "platform/lakehouse/dbt/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: platform/lakehouse/dbt
          file: platform/lakehouse/dbt/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ai-aas-hardened-lakehouse-dbt:latest
