# Mapbox API Key Secret for Superset
# Replace the placeholder with your actual Mapbox token
apiVersion: v1
kind: Secret
metadata:
  name: superset-mapbox
  namespace: aaas
type: Opaque
stringData:
  # IMPORTANT: Replace with your actual Mapbox API key
  # Get your key at: https://www.mapbox.com/
  MAPBOX_API_KEY: "pk.eyJ1Ijoiamd0b2xlbnRpbm8iLCJhIjoiY21jMmNycWRiMDc0ajJqcHZoaDYyeTJ1NiJ9.Dns6WOql16BUQ4l7otaeww"