apiVersion: batch/v1
kind: CronJob
metadata: { name: dbt-nightly, namespace: aaas }
spec:
  schedule: "0 18 * * *" # 02:00+08:00 Manila
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: dbt-runner
          containers:
            - name: dbt
              image: ghcr.io/REPO_OWNER/ai-aas-hardened-lakehouse-dbt:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests: { cpu: "200m", memory: "512Mi" }
                limits:   { cpu: "1", memory: "2Gi" }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: dbt-runner, namespace: aaas }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: { name: dbt-runner, namespace: aaas }
rules:
  - apiGroups: ["batch"] resources: ["jobs"] verbs: ["get","list","watch","create","delete"]
  - apiGroups: [""] resources: ["pods"] verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: { name: dbt-runner, namespace: aaas }
subjects: [ { kind: ServiceAccount, name: dbt-runner, namespace: aaas } ]
roleRef: { kind: Role, name: dbt-runner, apiGroup: rbac.authorization.k8s.io }
