name: CI Pipeline (Production)
on:
  push:
    branches: [ main ]           # ⬅️ no PRs
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ci-production-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}   # defense in depth
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Mark workspace safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup Node 20 + pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { version: 9 }

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm -w build

      - name: Test
        run: pnpm -w test