name: CI Pipeline
on: [push, pull_request]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI temporarily simplified - fix in progress"