name: Creative/Studio Agents Sweep
on: [pull_request]

jobs:
  sweep-creative:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: |
          curl -fsSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          chmod +x /usr/local/bin/yq
      - name: Sweep + Export + Gate (Repo Scope Only)
        env:
          MIN_AGENTS: 5
          FORMAT: table
        run: |
          chmod +x scripts/studio-agents-sweep.sh
          ./scripts/studio-agents-sweep.sh --update-registry --fail-on-unknown . | tee STUDIO_AGENTS.table
          FORMAT=csv  ./scripts/studio-agents-sweep.sh . > STUDIO_AGENTS.csv
          FORMAT=json ./scripts/studio-agents-sweep.sh . > STUDIO_AGENTS.json
      - uses: actions/upload-artifact@v4
        with:
          name: studio-agents
          path: |
            STUDIO_AGENTS.table
            STUDIO_AGENTS.csv
            STUDIO_AGENTS.json
            creative-studio/registry/creative-agents.yaml