name: Dataset Publisher Tests
on:
  pull_request:
    paths:
      - 'packages/**'
      - 'services/**'
      - 'apps/**'
      - '.github/workflows/dataset-publisher-tests.yml'
  push:
    branches: [main]
    paths:
      - 'packages/**'
      - 'services/**'
      - 'apps/**'
      - '.github/workflows/dataset-publisher-tests.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    # Skip for Dependabot PRs - dependency updates get basic validation elsewhere
    if: ${{ !(
      github.event_name == 'pull_request' && (
        github.actor == 'dependabot[bot]' ||
        startsWith(github.head_ref, 'dependabot/')
      )
    ) }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'pnpm' }
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Unit
        run: pnpm -r --workspace-concurrency 1 test --if-present
      - name: Integration
        run: pnpm -r --workspace-concurrency 1 run test:integration --if-present
      - name: Performance
        run: pnpm -r --workspace-concurrency 1 run test:perf --if-present
      - name: Upload results (non-fatal)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: comprehensive-test-report
          path: |
            test-results/
            test-temp/
          if-no-files-found: ignore