name: docs-site

on:
  pull_request:
    paths:
      - 'docs-site/**'
      - 'packages/**'
      - 'apps/**'
      - 'agents/**'
      - 'typedoc.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches: [main]
    paths:
      - 'docs-site/**'
      - 'typedoc.json'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # Skip Dependabot PRs; run on main and human PRs
    if: ${{ github.event_name == 'push' || (github.event.pull_request.user.login != 'dependabot[bot]' && !startsWith(github.head_ref, 'dependabot/')) }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate API docs (optional)
        run: pnpm run docs:api

      - name: Build Docusaurus site
        run: pnpm run docs:build

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: docs-site/build

      - name: Upload GitHub Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-site/build

  deploy-pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4