name: Documentation Site

on:
  push:
    branches: [main]
    paths:
      - 'docs-site/**'
      - 'packages/*/src/**'
      - 'apps/*/src/**'
      - 'agents/*/src/**'
      - 'typedoc.json'
      - 'package.json'
  pull_request:
    paths:
      - 'docs-site/**'
      - 'packages/*/src/**'
      - 'apps/*/src/**'
      - 'agents/*/src/**'
      - 'typedoc.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate API documentation
        run: |
          # Create TypeScript entry points if they don't exist
          mkdir -p packages/temp apps/temp agents/temp
          echo "export {};" > packages/temp/src/index.ts 2>/dev/null || true
          echo "export {};" > apps/temp/src/index.ts 2>/dev/null || true
          echo "export {};" > agents/temp/src/index.ts 2>/dev/null || true
          
          # Generate API docs (will fail gracefully if no TS files found)
          npm run docs:api || echo "No TypeScript files found for API generation"

      - name: Install docs dependencies
        run: cd docs-site && npm ci

      - name: Build documentation site
        run: cd docs-site && npm run build

      - name: Upload build artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-site/build

  deploy-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4