name: docs-validate
on:
  pull_request:
    paths: [ "docs/**", "blog/**", "sidebars.*", "docusaurus.config.*" ]
  push:
    paths: [ "docs/**", "blog/**", "sidebars.*", "docusaurus.config.*" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: chmod +x scripts/validate-docusaurus.sh
      - run: DAYS=30 scripts/validate-docusaurus.sh