name: Secret Scan
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Custom Secret Pattern Check
        run: |
          echo "🔍 Checking for Supabase tokens..."
          if grep -r "sbp_[A-Za-z0-9]" . --exclude-dir=.git --exclude-dir=node_modules; then
            echo "❌ Found Supabase PAT token in repository!"
            exit 1
          fi
          
          echo "🔍 Checking for JWT tokens..."
          if grep -r "eyJ[A-Za-z0-9_\-]*\." . --exclude-dir=.git --exclude-dir=node_modules; then
            echo "❌ Found JWT-like token in repository!"
            exit 1
          fi
          
          echo "🔍 Checking for service role references..."
          if grep -r "service_role" . --exclude-dir=.git --exclude-dir=node_modules --exclude="*.md" --exclude="*.sql"; then
            echo "❌ Found service_role reference in code!"
            exit 1
          fi
          
          echo "✅ No obvious secrets detected"