name: supabase-diff
on:
  schedule:
    - cron: "17 3 * * *"   # nightly 03:17 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with: { version: latest }

      - name: Configure env
        run: |
          echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "SUPABASE_PROJECT_REF=${{ secrets.SUPABASE_PROJECT_REF }}" >> $GITHUB_ENV
          echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }}" >> $GITHUB_ENV

      - name: Generate diff file (if any)
        run: scripts/supabase/db_diff_commit.sh

      - name: Create PR if there are changes
        if: ${{ hashFiles('supabase/migrations/*_auto.diff.sql') != '' }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(supabase): nightly schema diff"
          branch: chore/supabase-diff-${{ github.run_id }}
          title: "chore(supabase): nightly schema diff"
          body: |
            Auto-generated by CI.
            - Ensure migration is safe and idempotent.
            - Squash/Edit as needed before merge.
          labels: |
            area:infra
            supabase
